# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        14.0

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no
background_opacity 0.9
cursor_blink_interval 0

# Rose Pine (main/dark)
foreground              #e0def4
background              #191724
selection_foreground    #e0def4
selection_background    #403d52
cursor                  #524f67
cursor_text_color       #e0def4
url_color               #c4a7e7

# Tab bar
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
active_tab_foreground       #e0def4
active_tab_background       #26233a
inactive_tab_foreground     #6e6a86
inactive_tab_background     #191724

# Colors
color0  #26233a
color8  #6e6a86
color1  #eb6f92
color9  #eb6f92
color2  #31748f
color10 #31748f
color3  #f6c177
color11 #f6c177
color4  #9ccfd8
color12 #9ccfd8
color5  #c4a7e7
color13 #c4a7e7
color6  #ebbcba
color14 #ebbcba
color7  #e0def4
color15 #e0def4
