background {
    monitor =
    path = ~/wallpapers/exaria.png
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(c4a7e7)
    inner_color = rgb(191724)
    font_color = rgb(e0def4)
    placeholder_text = password
    position = 0, -100
    halign = center
    valign = center
}
